# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

env:
  TS_VER: 4
  SCRIPT_PREFIX: "npx tsx"
  GUM_INFO_FOREGROUND: "#7bd88f"
  GUM_INPUT_CURSOR_FOREGROUND: "#131313"
  GUM_INPUT_PROMPT_FOREGROUND: "#191919"
  GUM_INPUT_PROMPT: "> "
  GUM_INPUT_WIDTH: 120
  NODE_DEV_DIR:
    sh: |
      if [[ ${NODE_DEV_DIR+x} ]]; then
        echo ${NODE_DEV_DIR}
      else
        echo "${HOME}/WebstormProjects"
      fi

vars:
  IDE:
    sh: "{{.ROOT_DIR}}/scripts/ide.mts"

tasks:
  dependencies:
    internal: true
    silent: true
    cmd: "{{.ROOT_DIR}}/install.mts"

  dev-dir:
    internal: true
    silent: true
    cmd: mkdir -p {{.NODE_DEV_DIR}}
    deps:
      - dependencies
    generates:
      - "{{.NODE_DEV_DIR}}"

  express-gen-ts:
    desc:  Creates a new express application similar to the express-generator module using Typescript
    deps:
      - dev-dir
    summary: |
      NPM: https://www.npmjs.com/package/express-generator-typescript
      Github: https://github.com/seanpmaxwell/express-generator-typescript#readme
    vars:
      # prompts will execute in order
      PROJECT_NAME:
        sh: >-
          gum input --placeholder "Project Name?"

    cmds:
      - npx express-generator-typescript {{.PROJECT_NAME}}
      - "{{.IDE}} {{.PROJECT_NAME}}"
      - npm install --save-dev eslint @eslint/js @types/eslint__js typescript@^{{.TS_VER}} typescript-eslint {{.PROJECT_NAME}}
      - test -f {{.PROJECT_NAME}}/.eslintrc.json && rm {{.PROJECT_NAME}}/.eslintrc.json
      - test -f {{.PROJECT_NAME}}/.eslintignore && rm {{.PROJECT_NAME}}/.eslintignore
      - |
        cat << EOF > {{.PROJECT_NAME}}/eslint.config.mjs
        // @ts-check
        
        import eslint from '@eslint/js';
        import tseslint from 'typescript-eslint';
        
        export default tseslint.config(
          eslint.configs.recommended,
          ...tseslint.configs.recommended,
        );
        EOF
      - npm install ./{{.PROJECT_NAME}}
    dir:
      "{{.NODE_DEV_DIR}}"